import type { StepResult } from './journey.js';

export interface CapturedEvent {
  t: number;
  kind:
    | 'console'
    | 'pageerror'
    | 'request-failed'
    | 'response-error'
    | 'csp-violation'
    | 'a11y-violation'
    | 'css-health'
    | 'ui-overflow'
    | 'runtime-contrast'
    | 'runtime-images'
    | 'runtime-focus'
    | 'web-vitals'
    | 'aria-drift'
    | 'heading-order'
    | 'runtime-landmarks'
    | 'link-text'
    | 'placeholder-text'
    | 'tap-targets'
    | 'form-labels'
    | 'viewport-meta'
    | 'doc-title'
    | 'html-lang'
    | 'skip-link'
    | 'outbound-links'
    | 'autocomplete'
    | 'meta-description'
    | 'favicon'
    | 'mixed-content'
    | 'hsts'
    | 'x-frame-options'
    | 'referrer-policy'
    | 'font-loading'
    | 'cookie-security'
    | 'permissions-policy'
    | 'csp-policy'
    | 'coop'
    | 'coep'
    | 'sri'
    | 'info-leak'
    | 'corp'
    | 'cache-control'
    | 'vary'
    | 'inline-script'
    | 'trusted-types'
    | 'document-policy'
    | 'nel'
    | 'reporting-endpoints'
    | 'origin-agent-cluster'
    | 'link-underline'
    | 'cross-page-title'
    | 'cross-page-meta-description'
    | 'blank-main'
    | 'error-boundary-visible'
    | 'stuck-loading'
    | 'ui-error-text'
    | 'speculation-rules'
    | 'css-var'
    | 'visual-diff'
    | 'd0-violation';
  level?: string;
  text: string;
  url?: string;
  status?: number;
  stack?: string;
  impact?: 'minor' | 'moderate' | 'serious' | 'critical';
  ruleId?: string;
  /** css-health-only: severity bucket from cssHealth detector. */
  severity?: 'strict' | 'warn';
}

export interface Report {
  target: string;
  journey: string;
  viewport: { w: number; h: number };
  started: string;
  durationMs: number;
  counts: {
    consoleErrors: number;
    pageErrors: number;
    failedRequests: number;
    a11yViolations: number;
    cssHealthFindings: number;
    cssHealthFindingsStrict: number;
    uiOverflowFindings: number;
    uiOverflowFindingsStrict: number;
    runtimeContrastFindings: number;
    runtimeContrastFindingsStrict: number;
    runtimeImagesFindings: number;
    runtimeImagesFindingsStrict: number;
    runtimeFocusFindings: number;
    runtimeFocusFindingsStrict: number;
    webVitalsFindings: number;
    webVitalsFindingsStrict: number;
    tapTargetsFindings: number;
    tapTargetsFindingsStrict: number;
    formLabelsFindings: number;
    formLabelsFindingsStrict: number;
    viewportMetaFindings: number;
    viewportMetaFindingsStrict: number;
    docTitleFindings: number;
    docTitleFindingsStrict: number;
    htmlLangFindings: number;
    htmlLangFindingsStrict: number;
    skipLinkFindings: number;
    skipLinkFindingsStrict: number;
    outboundLinksFindings: number;
    outboundLinksFindingsStrict: number;
    autocompleteFindings: number;
    autocompleteFindingsStrict: number;
    metaDescriptionFindings: number;
    metaDescriptionFindingsStrict: number;
    faviconFindings: number;
    faviconFindingsStrict: number;
    mixedContentFindings: number;
    mixedContentFindingsStrict: number;
    hstsFindings: number;
    hstsFindingsStrict: number;
    xFrameOptionsFindings: number;
    xFrameOptionsFindingsStrict: number;
    referrerPolicyFindings: number;
    referrerPolicyFindingsStrict: number;
    fontLoadingFindings: number;
    fontLoadingFindingsStrict: number;
    cookieSecurityFindings: number;
    cookieSecurityFindingsStrict: number;
    permissionsPolicyFindings: number;
    permissionsPolicyFindingsStrict: number;
    cspFindings: number;
    cspFindingsStrict: number;
    coopFindings: number;
    coopFindingsStrict: number;
    coepFindings: number;
    coepFindingsStrict: number;
    sriFindings: number;
    sriFindingsStrict: number;
    infoLeakFindings: number;
    infoLeakFindingsStrict: number;
    corpFindings: number;
    corpFindingsStrict: number;
    cacheControlFindings: number;
    cacheControlFindingsStrict: number;
    varyFindings: number;
    varyFindingsStrict: number;
    inlineScriptFindings: number;
    inlineScriptFindingsStrict: number;
    trustedTypesFindings: number;
    trustedTypesFindingsStrict: number;
    documentPolicyFindings: number;
    documentPolicyFindingsStrict: number;
    nelFindings: number;
    nelFindingsStrict: number;
    reportingEndpointsFindings: number;
    reportingEndpointsFindingsStrict: number;
    originAgentClusterFindings: number;
    originAgentClusterFindingsStrict: number;
    linkUnderlineFindings: number;
    linkUnderlineFindingsStrict: number;
    crossPageTitleFindings: number;
    crossPageTitleFindingsStrict: number;
    crossPageMetaDescriptionFindings: number;
    crossPageMetaDescriptionFindingsStrict: number;
    cspViolations: number;
    total: number;
    stepsOk: number;
    stepsFailed: number;
  };
  events: CapturedEvent[];
  steps: StepResult[];
}

export interface Budget {
  newConsoleErrors: number;
  newPageErrors: number;
  newFailedRequests: number;
  newA11yViolations: number;
  newCssHealthStrict: number;
  newUiOverflowStrict: number;
  newRuntimeContrastStrict: number;
  newRuntimeImagesStrict: number;
  newRuntimeFocusStrict: number;
  newWebVitalsStrict: number;
  newCspViolations: number;
  newAriaDriftStrict: number;
  newHeadingOrderStrict: number;
  newRuntimeLandmarksStrict: number;
  newLinkTextStrict: number;
  newPlaceholderTextStrict: number;
  newlyBrokenSteps: number;
}
